services:
  db-rutas:
    image: pgrouting/pgrouting:15-3.3-3.4.1
    container_name: db-rutas
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_rutas
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-historial:
    image: mongo:7
    container_name: db-historial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: historial_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1000:80"
    depends_on:
      - db-rutas
    volumes:
      - pgadmin_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgadmin_data: