server:
  port: ${SERVER_PORT:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_JWT_ISSUER_URI}
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: routes-service
              uri: http://routes-service:8080
              predicates:
                - Path=/api/routes/**
              filters:
                - StripPrefix=2

            - id: history-service
              uri: http://history-service:8080
              predicates:
                - Path=/api/history/**
              filters:
                - StripPrefix=2

            - id: supabase-vehiculos
              uri: ${SUPABASE_URL}
              predicates:
                - Path=/api/vehiculos/**
              filters:
                - StripPrefix=2
                - PrefixPath=/rest/v1
                - AddRequestHeader=apikey, ${SUPABASE_ANON_KEY}

            - id: supabase-presupuestos
              uri: ${SUPABASE_URL}
              predicates:
                - Path=/api/presupuesto/**
              filters:
                - StripPrefix=2
                - PrefixPath=/rest/v1
                - AddRequestHeader=apikey, ${SUPABASE_ANON_KEY}

            - id: routes-service-docs
              uri: http://routes-service:8080
              predicates:
                - Path=/routes/v3/api-docs
              filters:
                - SetPath=/v3/api-docs

            - id: history-service-docs
              uri: http://history-service:8080
              predicates:
                - Path=/history/v3/api-docs
              filters:
                - SetPath=/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: routes-service
        url: /routes/v3/api-docs
      - name: history-service
        url: /history/v3/api-docs