spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: routes-service
              uri: http://routes-service:8080
              predicates:
                - Path=/api/routes/**
              filters:
              - StripPrefix=2

            - id: history-service
              uri: http://history-service:8080
              predicates:
                - Path=/api/history/**
              filters:
              - StripPrefix=2

server:
  port: 8080