spring.application.name=routes-service

spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
server.error.include-binding-errors=always
spring.jackson.serialization.write-dates-as-timestamps=false

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.max.block.ms=2000
logging.level.org.apache.kafka=ERROR
spring.kafka.producer.properties.spring.json.add.type.headers=false