SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.autopista (
    id bigint NOT NULL,
    nombre character varying(255),
    codigo character varying(255)
);

ALTER TABLE public.autopista OWNER TO admin;

ALTER TABLE public.autopista ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autopista_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.calendario_tarifario (
    id bigint NOT NULL,
    portico_id bigint
);

ALTER TABLE public.calendario_tarifario OWNER TO admin;

ALTER TABLE public.calendario_tarifario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendario_tarifario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.portico (
    id bigint NOT NULL,
    codigo character varying(255),
    latitud double precision NOT NULL,
    longitud double precision NOT NULL,
    nombre character varying(255),
    sentido character varying(255),
    autopista_id bigint
);

ALTER TABLE public.portico OWNER TO admin;


ALTER TABLE public.portico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.rango_horario (
    id bigint NOT NULL,
    hora_fin time(6) without time zone,
    hora_inicio time(6) without time zone,
    regla_id bigint
);

ALTER TABLE public.rango_horario OWNER TO admin;

ALTER TABLE public.rango_horario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rango_horario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.regla_tarifaria (
    id bigint NOT NULL,
    portico_id bigint
);

ALTER TABLE public.regla_tarifaria OWNER TO admin;

ALTER TABLE public.regla_tarifaria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regla_tarifaria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.regla_tarifaria_vehiculos (
    regla_id bigint NOT NULL,
    tipo_vehiculo character varying(255),
    CONSTRAINT regla_tarifaria_vehiculos_tipo_vehiculo_check CHECK (((tipo_vehiculo)::text = ANY ((ARRAY['AUTO'::character varying, 'MOTO'::character varying, 'CAMIONETA'::character varying, 'BUS'::character varying, 'CAMION'::character varying, 'CAMION_REMOLQUE'::character varying])::text[])))
);

ALTER TABLE public.regla_tarifaria_vehiculos OWNER TO admin;

CREATE TABLE public.regla_temporal (
    id bigint NOT NULL,
    tipo_dia character varying(255),
    tipo_tarifa character varying(255),
    calendario_id bigint,
    CONSTRAINT regla_temporal_tipo_dia_check CHECK (((tipo_dia)::text = ANY ((ARRAY['LABORAL'::character varying, 'SABADO_FESTIVO'::character varying, 'DOMINGO'::character varying])::text[]))),
    CONSTRAINT regla_temporal_tipo_tarifa_check CHECK (((tipo_tarifa)::text = ANY ((ARRAY['TBFP'::character varying, 'TBP'::character varying, 'TS'::character varying])::text[])))
);

ALTER TABLE public.regla_temporal OWNER TO admin;

ALTER TABLE public.regla_temporal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regla_temporal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.valor_tarifa (
    id bigint NOT NULL,
    tipo_tarifa character varying(255),
    valor numeric(38,2),
    regla_id bigint,
    CONSTRAINT valor_tarifa_tipo_tarifa_check CHECK (((tipo_tarifa)::text = ANY ((ARRAY['TBFP'::character varying, 'TBP'::character varying, 'TS'::character varying])::text[])))
);

ALTER TABLE public.valor_tarifa OWNER TO admin;

ALTER TABLE public.valor_tarifa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.valor_tarifa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.autopista
    ADD CONSTRAINT autopista_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.calendario_tarifario
    ADD CONSTRAINT calendario_tarifario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portico
    ADD CONSTRAINT portico_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rango_horario
    ADD CONSTRAINT rango_horario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.regla_tarifaria
    ADD CONSTRAINT regla_tarifaria_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.regla_temporal
    ADD CONSTRAINT regla_temporal_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.calendario_tarifario
    ADD CONSTRAINT ukidd4q630mpxyvmj3ag27hqhc UNIQUE (portico_id);


ALTER TABLE ONLY public.valor_tarifa
    ADD CONSTRAINT valor_tarifa_pkey PRIMARY KEY (id);
	
ALTER TABLE ONLY public.calendario_tarifario
    ADD CONSTRAINT fk7jjh72y3ewuj9wodr4v786jnd FOREIGN KEY (portico_id) REFERENCES public.portico(id);

ALTER TABLE ONLY public.portico
    ADD CONSTRAINT fk8k3y8fas14pqfiw2eg2dwns4t FOREIGN KEY (autopista_id) REFERENCES public.autopista(id);

ALTER TABLE ONLY public.regla_temporal
    ADD CONSTRAINT fkcpnhy35521lmer4pstktaiili FOREIGN KEY (calendario_id) REFERENCES public.calendario_tarifario(id);

ALTER TABLE ONLY public.regla_tarifaria_vehiculos
    ADD CONSTRAINT fkl1ygq5xq4gd9t3xcmxexpy6a2 FOREIGN KEY (regla_id) REFERENCES public.regla_tarifaria(id);

ALTER TABLE ONLY public.valor_tarifa
    ADD CONSTRAINT fkluml147m32qwcg2cd20r5n84u FOREIGN KEY (regla_id) REFERENCES public.regla_tarifaria(id);

ALTER TABLE ONLY public.regla_tarifaria
    ADD CONSTRAINT fkojr8l7ktfmfbnoewespryujbv FOREIGN KEY (portico_id) REFERENCES public.portico(id);

ALTER TABLE ONLY public.rango_horario
    ADD CONSTRAINT fks3ay86k3imp4jcw23c6dpnrp FOREIGN KEY (regla_id) REFERENCES public.regla_temporal(id);